### ISSUE TITLE
Coverage reporting

### ISSUE THREAD

**Issue by jenbutongit** [XGovFormBuilder/digital-form-builder#82]
**Is your feature request related to a problem? Please describe.**
@mileyd wants a code cov output!

**Comment by jenbutongit** [comment]
hey @mileyd, I've pushed a fix to https://github.com/XGovFormBuilder/digital-form-builder/tree/fix/code-coverage. feel free to merge or cherrypick etc. seems like master/runner didn't have model as a dependency so it couldn't `require` it.

**Comment by mileyd** [comment]
Still failed with the same issue Jen.

#!/bin/bash -eo pipefail
yarn test-cov
yarn run v1.22.4
$ NODE_ENV=test yarn flow && yarn lint && yarn test-lab-cov
$ /home/circleci/project/runner/node_modules/.bin/flow
Launching Flow server for /home/circleci/project/runner
Spawned flow server (pid=359)
Logs will go to /tmp/flow/zShomezScirclecizSprojectzSrunner.log
Monitor logs will go to /tmp/flow/zShomezScirclecizSprojectzSrunner.monitor_log
No errors!t. Server is handling a request (collating errors): \|
$ standard
standard: Unexpected linter output:

TypeError: Cannot read property 'range' of null
Occurred while linting /home/circleci/project/runner/src/server/index.js:12
    at SourceCode.getTokenBefore (/home/circleci/project/runner/node_modules/eslint/lib/source-code/token-store/index.js:298:18)
    at checkSpacingBefore (/home/circleci/project/runner/node_modules/eslint/lib/rules/template-curly-spacing.js:60:42)
    at TemplateElement (/home/circleci/project/runner/node_modules/eslint/lib/rules/template-curly-spacing.js:119:17)
    at /home/circleci/project/runner/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/circleci/project/runner/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/circleci/project/runner/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/home/circleci/project/runner/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/home/circleci/project/runner/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/home/circleci/project/runner/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)

If you think this is a bug in `standard`, open an issue: https://github.com/standard/standard/issues
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1

**Comment by jenbutongit** [comment]
You will have to run yarn build in the model repo, then run yarn install in the runner repo before trying to run the code-cov script
